server:
  port: 6666

# 数据源配置
spring:
  datasource:
    username: 
    password: 
    url: jdbc:mysql://127.0.0.1:3306/你的数据库名?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
  servlet:
    multipart:
#      设置单个文件大小
      max-file-size: 20MB
#      设置单词文件请求总大小
      max-request-size: 100MB

mybatis-plus:
  type-aliases-package: com.wzb.member.entity # 扫描实体类包
  #  xxxMapper.xml 文件路径
  mapper-locations: classpath:com/wzb/member/mapper/xml/**.xml
#日志级别
logging:
  level:
    com.wzb.member.mapper: debug

wzb:
  jwt:
    config:
      secretKey:  # 秘钥
      expires: 604800 # 7天

# 阿里云OSS配置
aliyun:
  oss:
    flag: false
    endpoint: 
    accessKeyId: 
    accessKeySecret:
    bucketName: 